AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CloudTrailLogGroup:
    Type: String
    Description: "The CloudWatch log group where CloudTrail writes the logs"
Resources:
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "User sign in"
  TopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - "sns:Publish"
            Resource: !Ref SNSTopic
  LoginMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref CloudTrailLogGroup
      FilterPattern: '{$.eventName = "ConsoleLogin"}'
      MetricTransformations:
      - MetricValue: 1
        MetricNamespace: !Sub "${AWS::StackName}"
        MetricName: ConsoleLogins
  ConsoleLoginAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 0
      Namespace: !Sub "${AWS::StackName}"
      MetricName: ConsoleLogins
      Statistic: Maximum
      Period: 60
      TreatMissingData: notBreaching
      ActionsEnabled: true
      AlarmActions:
      - !Ref SNSTopic
Outputs:
  SNSTopic:
    Value: !Ref SNSTopic
